#:kivy 1.10.1

<Screen01>:
    BoxLayout:
        Button:
            text: 'Goto Screen 02'
            background_color: (0, 0, 1, .8)
            on_press:
                # root.manager.transition.direction = 'left'
                root.manager.current = 'screen2'

<Screen02>:
    BoxLayout:
        Button:
            text: 'Goto Screen 01'
            background_color: (1, 0, 0, .8)
            on_press:
                # root.manager.transition.direction = 'right'
                root.manager.current = 'home'