#:kivy 1.10.1

GridLayout:
    DropDown:
        id: versionDropDown
        on_parent: self.dismiss()
        on_select: btn.text = '{}'.format(args[1])

        Button:
            text: 'First Item'
            height: '48dp'
            on_release: versionDropDown.select(self.text)

        Label:
            text: 'Second Item'
            height: '48dp'

        Button:
            text: 'Third Item'
            height: '48dp'
            on_release: versionDropDown.select(self.text)
