#:kivy 2.0.0

# colores:
#:import C kivy.utils.get_color_from_hex
#:set SPINNERFG C("424242")
#:set GREYSPINNER C("2c2c2c")
#:set SPINNERBGOP C("212121")

#:set font_s "14sp"

<SpinnerOption>:
    size_hint: None, None
    size: 100, 24
    background_normal: ""
    background_down: ""
    background_color: SPINNERBGOP
    spacing: [0, 0]
    border: [0, 0, 0, 0]
    font_size: font_s
    # bold: True
    # texto alineado a la izquierda:
    text_size: [80, 0]
    halign:'left'
    valign:'middle'

<MainScreen>:
    canvas.before:
        Color:
            rgb: SPINNERFG
        Rectangle:
            pos: self.pos
            size: self.size

    GridLayout:
        cols: 3
        rows: 1
        size_hint_x: None # Ahora la propiedad width determina el ancho del widget
        size_hint_y: 1 # La altura se mantiene como una fracción de la altura de su contenedor


        GridLayout:
            cols: 2
            rows: 1
            padding: [1,2,0,1]

            size_hint_x: None # Ahora la propiedad width determina el ancho del widget
            size_hint_y: 1 # La altura se mantiene como una fracción de la altura de su contenedor
            anchor_x: 'left'
            anchor_y: 'top'
            width: (root.width/(622/4))+150  #150

            # canvas.before:
            #     Color:
            #         rgb: [0, 1, 0]
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size


            Spinner:
                id: "dropdown"
                text: "GNU/" + root.set_platform_name()
                font_size: font_s
                values: "Windows", "Mac", "GNU/Linux"
                size_hint: (None, None)
                size: (100, 30)
                on_text: root.print_current(self.text)
                background_normal: "views/assets/dropdown.png"
                background_down: "views/assets/dropdown_down.png"
                
            Spinner:
                id: "arch"
                text: root.set_architecture()
                font_size: font_s
                values: "64Bit", "32Bit"
                size_hint: (None, None)
                size: (50, 30)
                on_text: root.print_current(self.text)
                background_normal: "views/assets/dropdown_small.png"
                background_down: "views/assets/dropdown_down_small.png"
            
        # Tabs:
        GridLayout:
            cols: 1
            rows: 1
            padding: [2, 0, 0, 0]

            size_hint_x: None # Desactiva la redimensión automática para el eje x
            size_hint_y: 1 # Permite la redimensión automática para el eje y
            width: root.width-265 # 355 # Ancho deseado

            anchor_x: 'left'
            anchor_y: 'top'

            # canvas.before:
            #     Color:
            #         rgb: [0, 1, 0]
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size

            # background_color: GREYSPINNER

            TabbedPanel:
                id: tab_panel
                do_default_tab: False
                size_hint: (None, None)
                tab_pos: 'top_left'
                tab_height: 30
                size: (350, root.height-4)
                background_image: ""
                background_color: [0, 0, 0, 0]

                TabbedPanelItem:
                    text: 'Installed'
                    font_size: font_s
                    width: 112
                    height: 30
                    background_normal: "views/assets/tabs.png"
                    background_down: "views/assets/tabs_down.png"
                    
                    GridLayout:
                        cols: 1
                        rows: 1
                        size_hint: (None, None)

                        anchor_x: 'left'
                        anchor_y: 'top'

                        canvas.before:
                            Color:
                                rgb: GREYSPINNER
                            Rectangle:
                                pos: (2, 4)
                                size: (root.width-self.size[0]-20, root.height-self.size[1]+60)
                        Label:
                            text: 'List of installed versions'
                            size_hint: (None, None)

                TabbedPanelItem:
                    text: 'Stable'
                    font_size: font_s
                    width: 112
                    height: 30
                    background_normal: "views/assets/tabs.png"
                    background_down: "views/assets/tabs_down.png"

                    GridLayout:
                        cols: 1
                        rows: 1
                        size_hint: (None, None)

                        anchor_x: 'left'
                        anchor_y: 'top'

                        canvas.before:
                            Color:
                                rgb: GREYSPINNER
                            Rectangle:
                                pos: (2, 4)
                                size: (root.width-self.size[0]-20, root.height-self.size[1]+60)
                        Label:
                            text: 'List of stable versions avalidable in remote servers'
                            size_hint: (None, None)
                
                TabbedPanelItem:
                    text: 'BuildBot'
                    font_size: font_s
                    width: 112
                    height: 30
                    background_normal: "views/assets/tabs.png"
                    background_down: "views/assets/tabs_down.png"

                    GridLayout:
                        cols: 1
                        rows: 1
                        size_hint: (None, None)
                        
                        anchor_x: 'left'
                        anchor_y: 'top'

                        canvas.before:
                            Color:
                                rgb: GREYSPINNER
                            Rectangle:
                                pos: (2, 4)
                                size: (root.width-self.size[0]-20, root.height-self.size[1]+60)
                        
                        Label:
                            text: 'List of buildbots versions avalidable in remote servers'
                            size_hint: (None, None)
 
        

        # buttons side bar
        GridLayout:
            cols: 1
            rows: 1

            size_hint_x: None # Ahora la propiedad width determina el ancho del widget
            size_hint_y: 1 # La altura se mantiene como una fracción de la altura de su contenedor

            padding: [-6, 35, 0, 0]

            width: 116 # 115 # Ancho deseado
            height: 84

            anchor_x: 'left'
            anchor_y: 'top'

            # canvas.before:
            #     Color:
            #         rgb: [0, 1, 0]
            #     Rectangle:
            #         pos: self.pos
            #         size: self.size

            GridLayout:
                cols: 1
                rows: 3

                size_hint: (1, None)
                
                # width: root.width-115 # 115 # Ancho deseado
                height: 84

                anchor_x: 'left'
                anchor_y: 'top'
                
                padding: [2, 2, 2, 2]

                # canvas.before:
                #     Color:
                #         rgb: [1, 0, 0]
                #     Rectangle:
                #         pos: self.pos 
                #         size: self.size
                
                Button:
                    id: "button_download"
                    text: 'Download'
                    font_size: font_s
                    background_normal: "views/assets/button.png"
                    background_down: "views/assets/button_down.png"
                    size_hint: (None, None)
                    width: 112
                    height: 28                    

                Button:
                    id: "button_launch"
                    text: 'Launch'
                    font_size: font_s
                    background_normal: "views/assets/button.png"
                    background_down: "views/assets/button_down.png"
                    size_hint: (None, None)
                    width: 112
                    height: 28

                Button:
                    id: "button_settings"
                    text: 'Settings'
                    font_size: font_s
                    background_normal: "views/assets/button.png"
                    background_down: "views/assets/button_down.png"
                    size_hint: (None, None)
                    width: 112
                    height: 28
                    on_press:
                        root.manager.transition.direction = 'down'
                        root.manager.current = 'settings'



<PreferencesScreen>:
    canvas.before:
        Color:
            rgb: SPINNERFG
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        padding: "5sp"
        spacing: "8sp"
        Button:
            text: 'Come back'
            background_color: (1, 0, 0, .8)
            on_press:
                root.manager.transition.direction = 'up'
                root.manager.current = 'main_screen'
        
        Button:
            text: 'boton2'
            background_color: (0, 1, 0, .8)

