#:kivy 1.11.1

# colores:
#:import C kivy.utils.get_color_from_hex
#:set SPINNERFG C("424242")
#:set SPINNERBGOP C("212121")

<SpinnerOption>:
    size_hint: None, None
    size: 100, 24
    background_normal: ""
    background_down: ""
    background_color: SPINNERBGOP
    spacing: [0, 0]
    border: [0, 0, 0, 0]
    font_size: "10sp"
    bold: True
    # texto alineado a la izquierda:
    text_size: [80, 0]
    halign:'left'
    valign:'middle'

<MainScreen>:
    canvas.before:
        Color:
            rgb: (66/255.0, 66/255.0, 66/255.0)
        Rectangle:
            pos: self.pos
            size: self.size

    GridLayout:
        id: "gl0"
        cols: 2
        rows: 1
        spacing: [5, 5]
        padding: [5, 5, 5, 5]

        GridLayout:
            id: "gl1"
            cols: 2
            rows: 1
            spacing: [5, 5]
            padding: [5, 5, 5, 5]
            Spinner:
                id: "dropdown"
                text: root.set_platform_name()
                values: "Windows", "Mac", "GNU/Linux"
                size_hint: (None, None)
                size: (100, 24)
                on_text: root.print_current(self.text)
                background_normal: "views/assets/dropdown.png"
                background_down: "views/assets/dropdown_down.png"
                border: [0, 0, 0, 0]
                font_size: "10sp"
                bold: True
                # texto alineado a la izquierda:
                text_size: [80, 0]
                halign:'left'
                valign:'middle'

            Spinner:
                id: "arch"
                text: "64"
                values: "64", "32"
                size_hint: (None, None)
                size: (38, 24)
                on_text: root.print_current(self.text)
                background_normal: "views/assets/dropdown_small.png"
                background_down: "views/assets/dropdown_down_small.png"
                border: [0, 0, 0, 0]
                font_size: "10sp"
                bold: True
                # texto alineado a la izquierda:
                text_size: [25, 0]
                halign:'left'
                valign:'middle'
        GridLayout:
            id: "gl1"
            cols: 1
            rows: 1
            spacing: [5, 5]
            padding: [5, 5, 5, 5]
            # 1.0 es igual a 100%
            size_hint: (None, 1.0)
            width: 122
            Button:
                id: "button01"
                text: 'Settings'
                background_normal: "views/assets/button.png"
                background_down: "views/assets/button_down.png"
                size_hint: (None, None)
                width: 112
                height: 24
                font_size: "10sp"
                bold: True
                on_press:
                    root.manager.transition.direction = 'down'
                    root.manager.current = 'screen2'


<TabbedPanelDemo>:
    TabbedPanelItem:
        text: 'first tab'
        Label:
            text: 'First tab content area'
    TabbedPanelItem:
        text: 'tab2'
        BoxLayout:
            Label:
                text: 'Second tab content area'
            Button:
                text: 'Button that does nothing'
    TabbedPanelItem:
        text: 'tab3'
        RstDocument:
            text:
                '\\n'.join(("Hello world", "-----------",
                "You are in the third tab."))


<PreferencesScreen>:
    canvas.before:
        Color:
            rgb: (66/255.0, 66/255.0, 66/255.0)
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        padding: "5sp"
        spacing: "8sp"
        Button:
            text: 'Goto Screen 01'
            background_color: (1, 0, 0, .8)
            on_press:
                root.manager.transition.direction = 'up'
                root.manager.current = 'home'
        
        Button:
            text: 'boton2'
            background_color: (0, 1, 0, .8)

